ui:
  image: uifd/ui-for-docker:0.11.0 
  container_name: ui
  privileged: true
  ports:
    - 9000:9000
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

odoo:
  build: .
  container_name: odoo
  links:
    - postgres
  ports:
    - 8069:8069    
  environment:
    - DB_HOST=postgres
    - DB_PORT=5432
    - DB_USER=odoo
    - DB_PASSWORD=odoo

postgres:
  image: postgres:9.6.1-alpine  
  container_name: postgres
  ports:
    - 5432:5432
  environment:
    - POSTGRES_USER=odoo
    - POSTGRES_PASSWORD=odoo
  volumes:
    - /opt/docker/data/postgres/data:/var/lib/postgresql/data:rw